services:
  postgres_tyres:
    image: postgres:15
    env_file: ./.env
    environment:
      POSTGRES_USER: ${TYRES_DB_USER}
      POSTGRES_PASSWORD: ${TYRES_DB_PASSWORD}
      POSTGRES_DB: ${TYRES_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - tyre_data:/var/lib/postgresql/data
    networks:
      - labnet

  postgres_users:
    image: postgres:15
    env_file: ./.env
    environment:
      POSTGRES_USER: ${USERS_DB_USER}
      POSTGRES_PASSWORD: ${USERS_DB_PASSWORD}
      POSTGRES_DB: ${USERS_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - users_data:/var/lib/postgresql/data
    networks:
      - labnet

  tyres_service:
    image: ghcr.io/andrewfoxatu/cicd2-tyres-service/tyres_service:latest
    env_file: ./.env
    environment:
      POSTGRES_HOST: ${TYRES_DB_HOST}
      POSTGRES_PORT: ${TYRES_DB_PORT}
      POSTGRES_DB: ${TYRES_DB_NAME}
      POSTGRES_USER: ${TYRES_DB_USER}
      POSTGRES_PASSWORD: ${TYRES_DB_PASSWORD}
    depends_on:
      - postgres_tyres
    ports:
      - "8001:8000"
    networks:
      - labnet

  users_service:
    image: ghcr.io/andrewfoxatu/cicd2-users-service/users_service:latest
    env_file: ./.env
    environment:
      POSTGRES_HOST: ${USERS_DB_HOST}
      POSTGRES_PORT: ${USERS_DB_PORT}
      POSTGRES_DB: ${USERS_DB_NAME}
      POSTGRES_USER: ${USERS_DB_USER}
      POSTGRES_PASSWORD: ${USERS_DB_PASSWORD}
    depends_on:
      - postgres_users
    ports:
      - "8003:8000"
    networks:
      - labnet

  frontend:
    image: ghcr.io/andrewfoxatu/cicd2-frontend/frontend:latest
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - users_service
      - tyres_service
    networks:
      - labnet



networks:
  labnet:

volumes:
  tyre_data:
  users_data:
